use_frameworks!

platform :ios, '9.0'

target 'YYBaseCore_Example' do
  pod 'YYBaseCore', :path => '../'

  target 'YYBaseCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
